name: sev01
description: SoftwareEngeneering.

publish_to: 'none' 

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:  ^0.1.3
  flutter_staggered_grid_view: "^0.3.0"
  http: ^0.12.1
  url_launcher: ^5.2.5
  flutter_webview_plugin:
  webview_flutter: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true



 
